language: php
dist: trusty

php:
    - 5.6
    - hhvm
    - 7
    - 7.1
# PHP 7.2 was segfaulting on 13-11-2017. try later again
#    - 7.2

before_install:
    - composer self-update

install:
    - composer install --prefer-source

script:
    - ./vendor/bin/phpunit --coverage-text
