language: php
dist: trusty

php:
    - 5.6
    - hhvm
    - 7
    - 7.1
    - 7.2

before_install:
    - composer self-update

install:
    - composer install --prefer-source

script:
    - ./vendor/bin/phpunit --coverage-text
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then composer require phpstan/phpstan; ./vendor/bin/phpstan analyze -l 7 src/; fi
